version: "1.1"
pipeline:
  name: bw-test-2
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1 >> stage_2 >> stage_3
  usage_stats: false
stages:
  stage_1:
    executable_module_path: stage_one/main.py
    args: ["Hello", "World"]
    cpu_request: 0.1
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
  stage_2:
    executable_module_path: stage_two/main.py
    cpu_request: 0.1
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 30
      retries: 2
    requirements:
       - requests
  stage_3:
    executable_module_path: stage_three/main.py
    cpu_request: 0.1
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 15
      replicas: 2
      port: 6000
      ingress: true
    requirements:
      - flask
logging:
  log_level: DEBUG
